@extends('layouts.app')

@section('content')
<div class="px-4 sm:px-4 md:px-20 lg:px-20">
    <h1 class="text-3xl mb-5">Terms & Services</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sollicitudin lorem. Vestibulum rhoncus faucibus placerat. Mauris a fermentum elit. Vivamus tincidunt tortor molestie, tristique velit in, sagittis sapien. Vivamus pretium convallis gravida. Ut id purus massa. Vivamus fermentum eros id rutrum lacinia.

        Praesent arcu libero, porta id lectus vel, tincidunt imperdiet augue. Suspendisse potenti. Aenean eros turpis, dapibus in bibendum a, consectetur eget risus. Fusce eget ex nulla. Morbi vestibulum pharetra tortor ut sagittis. Nam mattis consectetur faucibus. Integer euismod, erat non vehicula viverra, leo lectus ornare mauris, in viverra sapien dui vel diam. In ac dui sed nunc sodales gravida. Integer vehicula ultrices hendrerit. Vivamus id ullamcorper magna. Nullam metus elit, facilisis egestas magna nec, porttitor convallis felis. Vestibulum odio urna, vulputate sit amet commodo ut, sagittis quis urna. Etiam varius turpis a risus ornare, eu pretium sapien ullamcorper.
        
        Praesent sed finibus erat, non elementum sapien. Praesent vehicula semper vehicula. In ut scelerisque diam, eu tempor massa. Aliquam tincidunt risus ut tincidunt porta. Sed elit ante, scelerisque iaculis leo id, fringilla facilisis ligula. In hac habitasse platea dictumst. Phasellus aliquet tortor eget mauris dictum vehicula in in ex.
        
        Ut ut maximus quam. Maecenas euismod, massa eget dictum egestas, lacus est finibus elit, ut pellentesque dolor lacus nec nibh. Cras sollicitudin vehicula ligula, et condimentum tortor consequat sit amet. Proin aliquam diam nec odio tempor, non semper lorem imperdiet. Curabitur ac efficitur mauris, luctus semper tellus. Ut nunc libero, feugiat eu diam et, ornare tempus risus. Quisque rutrum est ut elit lacinia faucibus. Mauris ac volutpat sem, sit amet luctus metus. Quisque eu leo at justo condimentum imperdiet eget ac ligula. Maecenas porta ligula sit amet tortor hendrerit, vitae bibendum est vehicula. Nunc at turpis est. In tincidunt imperdiet nulla, sed vestibulum dolor iaculis a. Praesent luctus, ligula sed rutrum hendrerit, urna eros aliquet urna, vitae dapibus dolor lacus at erat. Etiam sed aliquet erat. Sed tellus est, volutpat quis ullamcorper eget, pharetra at nulla. Integer sit amet rutrum dolor, ac sagittis nibh.
        
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus consectetur felis eget lectus iaculis, non fermentum ante porta. Nunc gravida diam sit amet urna eleifend rhoncus vel in metus. Curabitur euismod tortor risus, nec faucibus elit tincidunt sit amet. Cras tellus diam, tempus a cursus vitae, porta mollis erat. Praesent turpis libero, ornare nec lorem eget, euismod finibus ligula. In rutrum varius mi, et lobortis nunc elementum at. Cras ultricies erat et vehicula gravida. Proin elementum efficitur posuere. Fusce porttitor venenatis magna, ac volutpat arcu eleifend a.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sollicitudin lorem. Vestibulum rhoncus faucibus placerat. Mauris a fermentum elit. Vivamus tincidunt tortor molestie, tristique velit in, sagittis sapien. Vivamus pretium convallis gravida. Ut id purus massa. Vivamus fermentum eros id rutrum lacinia.

        Praesent arcu libero, porta id lectus vel, tincidunt imperdiet augue. Suspendisse potenti. Aenean eros turpis, dapibus in bibendum a, consectetur eget risus. Fusce eget ex nulla. Morbi vestibulum pharetra tortor ut sagittis. Nam mattis consectetur faucibus. Integer euismod, erat non vehicula viverra, leo lectus ornare mauris, in viverra sapien dui vel diam. In ac dui sed nunc sodales gravida. Integer vehicula ultrices hendrerit. Vivamus id ullamcorper magna. Nullam metus elit, facilisis egestas magna nec, porttitor convallis felis. Vestibulum odio urna, vulputate sit amet commodo ut, sagittis quis urna. Etiam varius turpis a risus ornare, eu pretium sapien ullamcorper.
        
        Praesent sed finibus erat, non elementum sapien. Praesent vehicula semper vehicula. In ut scelerisque diam, eu tempor massa. Aliquam tincidunt risus ut tincidunt porta. Sed elit ante, scelerisque iaculis leo id, fringilla facilisis ligula. In hac habitasse platea dictumst. Phasellus aliquet tortor eget mauris dictum vehicula in in ex.
        
        Ut ut maximus quam. Maecenas euismod, massa eget dictum egestas, lacus est finibus elit, ut pellentesque dolor lacus nec nibh. Cras sollicitudin vehicula ligula, et condimentum tortor consequat sit amet. Proin aliquam diam nec odio tempor, non semper lorem imperdiet. Curabitur ac efficitur mauris, luctus semper tellus. Ut nunc libero, feugiat eu diam et, ornare tempus risus. Quisque rutrum est ut elit lacinia faucibus. Mauris ac volutpat sem, sit amet luctus metus. Quisque eu leo at justo condimentum imperdiet eget ac ligula. Maecenas porta ligula sit amet tortor hendrerit, vitae bibendum est vehicula. Nunc at turpis est. In tincidunt imperdiet nulla, sed vestibulum dolor iaculis a. Praesent luctus, ligula sed rutrum hendrerit, urna eros aliquet urna, vitae dapibus dolor lacus at erat. Etiam sed aliquet erat. Sed tellus est, volutpat quis ullamcorper eget, pharetra at nulla. Integer sit amet rutrum dolor, ac sagittis nibh.
        
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus consectetur felis eget lectus iaculis, non fermentum ante porta. Nunc gravida diam sit amet urna eleifend rhoncus vel in metus. Curabitur euismod tortor risus, nec faucibus elit tincidunt sit amet. Cras tellus diam, tempus a cursus vitae, porta mollis erat. Praesent turpis libero, ornare nec lorem eget, euismod finibus ligula. In rutrum varius mi, et lobortis nunc elementum at. Cras ultricies erat et vehicula gravida. Proin elementum efficitur posuere. Fusce porttitor venenatis magna, ac volutpat arcu eleifend a.
    </p>
</div>
@endsection